//
// FavoriteStore.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct FavoriteStore: Codable {

    public var id: Int64
    public var name: String
    public var image: String

    public init(id: Int64, name: String, image: String) {
        self.id = id
        self.name = name
        self.image = image
    }


}

