//
// Favorite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Favorite: Codable {

    public var userId: Int64
    public var favoriteNum: Int
    public var favoriteStores: [FavoriteStore]

    public init(userId: Int64, favoriteNum: Int, favoriteStores: [FavoriteStore]) {
        self.userId = userId
        self.favoriteNum = favoriteNum
        self.favoriteStores = favoriteStores
    }


}

