//
// Food.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Food: Codable {

    public var id: Int64
    /** Number of items in foods. */
    public var foodNum: Int
    public var foods: [FoodItem]

    public init(id: Int64, foodNum: Int, foods: [FoodItem]) {
        self.id = id
        self.foodNum = foodNum
        self.foods = foods
    }


}

