//
// FoodCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct FoodCreate: Codable {

    public var id: Int64
    public var name: String
    public var originalPrice: Int
    public var salePrice: Int
    public var startTime: String
    public var endTime: String
    public var number: Int
    public var allergy: String
    public var image: String
    public var storeId: Int64
    public var storeName: String

    public init(id: Int64, name: String, originalPrice: Int, salePrice: Int, startTime: String, endTime: String, number: Int, allergy: String, image: String, storeId: Int64, storeName: String) {
        self.id = id
        self.name = name
        self.originalPrice = originalPrice
        self.salePrice = salePrice
        self.startTime = startTime
        self.endTime = endTime
        self.number = number
        self.allergy = allergy
        self.image = image
        self.storeId = storeId
        self.storeName = storeName
    }


}

