//
// StoreItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct StoreItem: Codable {

    public var id: Int64
    public var name: String
    public var originalPrice: Int
    public var salePrice: Int
    public var startTime: String
    public var endTime: String
    public var image: String

    public init(id: Int64, name: String, originalPrice: Int, salePrice: Int, startTime: String, endTime: String, image: String) {
        self.id = id
        self.name = name
        self.originalPrice = originalPrice
        self.salePrice = salePrice
        self.startTime = startTime
        self.endTime = endTime
        self.image = image
    }


}

