//
// Store.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Store: Codable {

    public var id: Int64
    public var name: String
    public var image: String
    /** Number of items in foods. */
    public var foodNum: Int
    public var foods: [StoreItem]

    public init(id: Int64, name: String, image: String, foodNum: Int, foods: [StoreItem]) {
        self.id = id
        self.name = name
        self.image = image
        self.foodNum = foodNum
        self.foods = foods
    }


}

