---
format_version: '8'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios
workflows:
  deploy:
    steps:
    - activate-ssh-key@4.0.3:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.14: {}
    - cache-pull@2.0.1: {}
    - script@1.1.5:
        title: Do anything with Script step
    - recreate-user-schemes@1.0.2:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
    - cocoapods-install@1.7.2: {}
    - ios-auto-provision@1.3.1:
        inputs:
        - distribution_type: ad-hoc
    - xcode-test@2.3.2:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
    - xcode-archive@2.5.0:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
        - export_method: "$BITRISE_EXPORT_METHOD"
    - deploy-to-bitrise-io@1.6.0: {}
    - deploygate--upload-app-bitrise-step@1.0.1:
        inputs:
        - app_path: "$BITRISE_IPA_PATH"
        - visibility: public
        - api_key: "$API_Key"
        - owner_name: looker
    - cache-push@2.2.0: {}
  develop:
    steps:
    - activate-ssh-key@4.0.3:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.14: {}
    - cache-pull@2.0.1: {}
    - script@1.1.5:
        title: Do anything with Script step
    - certificate-and-profile-installer@1.10.1: {}
    - recreate-user-schemes@1.0.2:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
    - cocoapods-install@1.7.2: {}
    - xcode-test@2.3.2:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
    - xcode-archive@2.6.0: {}
    - deploy-to-bitrise-io@1.6.0: {}
    - deploygate--upload-app-bitrise-step@1.0.1:
        inputs:
        - app_path: "$BITRISE_IPA_PATH"
        - visibility: public
        - api_key: "$APIKey"
        - message: "$GIT_CLONE_COMMIT_MESSAGE_SUBJECT"
        - owner_name: looker
    - slack@3.1.3:
        inputs:
        - webhook_url: "$WEBHOOK_URL"
        - from_username: Bitrise CI
        - emoji: ":ichikawa:"
app:
  envs:
  - opts:
      is_expand: false
    BITRISE_PROJECT_PATH: ETASTE/ETASTE/ETASTE.xcworkspace
  - opts:
      is_expand: false
    BITRISE_SCHEME: ETASTE
  - opts:
      is_expand: false
    BITRISE_EXPORT_METHOD: development
trigger_map:
- push_branch: develop
  workflow: develop
- pull_request_source_branch: "*"
  pull_request_target_branch: develop
  workflow: develop
