//
// Allergy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Allergy: Codable {

    public var _id: Int
    public var name: String

    public init(_id: Int, name: String) {
        self._id = _id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
    }


}

