//
// FavoriteCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct FavoriteCreate: Codable {

    public var userId: Int64
    public var storeId: Int64
    public var storeName: String

    public init(userId: Int64, storeId: Int64, storeName: String) {
        self.userId = userId
        self.storeId = storeId
        self.storeName = storeName
    }


}

