//
// FavoriteStore.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct FavoriteStore: Codable {

    public var _id: Int64
    public var name: String
    public var image: String

    public init(_id: Int64, name: String, image: String) {
        self._id = _id
        self.name = name
        self.image = image
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case image
    }


}

