//
// Food.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Food: Codable {

    public var _id: Int64
    /** Number of items in foods. */
    public var foodNum: Int
    public var foods: [FoodItem]

    public init(_id: Int64, foodNum: Int, foods: [FoodItem]) {
        self._id = _id
        self.foodNum = foodNum
        self.foods = foods
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case foodNum
        case foods
    }


}

