//
// FoodDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct FoodDetail: Codable {

    public var _id: Int64
    public var isSaling: String
    public var foodInfo: [FoodItem]
    public var storeInfo: [Store]

    public init(_id: Int64, isSaling: String, foodInfo: [FoodItem], storeInfo: [Store]) {
        self._id = _id
        self.isSaling = isSaling
        self.foodInfo = foodInfo
        self.storeInfo = storeInfo
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case isSaling
        case foodInfo
        case storeInfo
    }


}

