//
// Store.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Store: Codable {

    public var _id: Int64
    public var name: String
    public var image: String
    /** Number of items in foods. */
    public var foodNum: Int
    public var foods: [StoreItem]

    public init(_id: Int64, name: String, image: String, foodNum: Int, foods: [StoreItem]) {
        self._id = _id
        self.name = name
        self.image = image
        self.foodNum = foodNum
        self.foods = foods
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case image
        case foodNum
        case foods
    }


}

