//
// TradeCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct TradeCreate: Codable {

    public var _id: Int64
    public var userId: Int64
    public var stodeId: Int64
    public var foodId: Int64
    public var amount: Int
    public var receiveTime: String

    public init(_id: Int64, userId: Int64, stodeId: Int64, foodId: Int64, amount: Int, receiveTime: String) {
        self._id = _id
        self.userId = userId
        self.stodeId = stodeId
        self.foodId = foodId
        self.amount = amount
        self.receiveTime = receiveTime
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case userId
        case stodeId
        case foodId
        case amount
        case receiveTime
    }


}

