//
// TradeStore.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct TradeStore: Codable {

    public var _id: Int64
    public var foodName: String
    public var amount: Int
    public var startTime: String
    public var endTime: String
    public var foodImage: String
    public var tradeNum: Int?
    public var storeTrades: [TradeStoreItem]

    public init(_id: Int64, foodName: String, amount: Int, startTime: String, endTime: String, foodImage: String, tradeNum: Int?, storeTrades: [TradeStoreItem]) {
        self._id = _id
        self.foodName = foodName
        self.amount = amount
        self.startTime = startTime
        self.endTime = endTime
        self.foodImage = foodImage
        self.tradeNum = tradeNum
        self.storeTrades = storeTrades
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case foodName
        case amount
        case startTime
        case endTime
        case foodImage
        case tradeNum
        case storeTrades
    }


}

