//
// Trade.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Trade: Codable {

    public var _id: Int64
    /** Number of items in trades. */
    public var tradeNum: Int
    public var trades: [TradeItem]

    public init(_id: Int64, tradeNum: Int, trades: [TradeItem]) {
        self._id = _id
        self.tradeNum = tradeNum
        self.trades = trades
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case tradeNum
        case trades
    }


}

