//
// TradeStoreItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct TradeStoreItem: Codable {

    public var _id: Int64
    public var orderAmount: Int
    public var totalPrice: Int
    public var recieveTime: String
    public var userName: String
    public var isCompleted: String

    public init(_id: Int64, orderAmount: Int, totalPrice: Int, recieveTime: String, userName: String, isCompleted: String) {
        self._id = _id
        self.orderAmount = orderAmount
        self.totalPrice = totalPrice
        self.recieveTime = recieveTime
        self.userName = userName
        self.isCompleted = isCompleted
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case orderAmount
        case totalPrice
        case recieveTime
        case userName
        case isCompleted
    }


}

