//
// TradeItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct TradeItem: Codable {

    public var _id: Int64
    public var foodId: Int64
    public var stodeId: Int64
    public var foodName: String
    public var storeName: String
    public var amount: Int
    public var totalPrice: Int
    public var recieveTime: String
    public var isCompleted: String
    public var foodImage: String

    public init(_id: Int64, foodId: Int64, stodeId: Int64, foodName: String, storeName: String, amount: Int, totalPrice: Int, recieveTime: String, isCompleted: String, foodImage: String) {
        self._id = _id
        self.foodId = foodId
        self.stodeId = stodeId
        self.foodName = foodName
        self.storeName = storeName
        self.amount = amount
        self.totalPrice = totalPrice
        self.recieveTime = recieveTime
        self.isCompleted = isCompleted
        self.foodImage = foodImage
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case foodId
        case stodeId
        case foodName
        case storeName
        case amount
        case totalPrice
        case recieveTime
        case isCompleted
        case foodImage
    }


}

