# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

# platform :ios, '9.0'

target 'ETASTE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ETASTE
   pod 'GoogleMaps'


  target 'ETASTETests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ETASTEUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
